### ISSUE TITLE
Code update as on your server?

### ISSUE THREAD

**Issue by mkgin** [VigibotDev/meshtastic-d3js#2]
Is it possible to update the code in this repo to work as it does on https://www.serveurperso.com/ ? Perhaps even as a development fork?

**Comment by ServeurpersoCom** [comment]
Yes the version of this repo is obsolete, I will update as soon as I have implemented the bidirectional traceroute with SNR of 2.5.x because in the Meshtastic firmware, the Neighbor info will no longer be transmitted by LoRa, but only by MQTT, so the traceroute frame will become the first source of the graph.

**Comment by mkgin** [comment]
Interesting... I haven't been following much of the changes with 2.5.x. Looking forward to the update. No pressure. :-)
